name: 'Code Review Action'
description: 'Runs an AI powered code review on a pull request'
inputs:
  github_repo:
    description: 'The github repo, in the format owner/repo'
    required: true
  github_pr_number:
    description: 'The pull request number'
    required: true
  github_base_branch:
    description: 'The base branch of the pull request'
    required: true
    default: main
  github_active_branch:
    description: 'The active branch of the pull request'
    required: true
  github_app_id:
    description: 'The GitHub App ID'
    required: true
  github_app_private_key:
    description: 'The GitHub App private key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/app/entrypoint.sh'
# Expected environment variables:
# - OPENAI_API_KEY - OpenAI API key
# - LANGCHAIN_TRACING_V2 - Boolean flag to enable LangSmith tracing
# - LANGCHAIN_API_KEY - LangChain API key to use for LangSmith tracing
# - LANGCHAIN_PROJECT - LangSmith project to associate for tracing
